### ISSUE TITLE
Support knex migration script for keystone-next projects

### ISSUE THREAD

**Issue by MurzNN** [josemf/keystone-adapter-knex-migrations#11]
Does the `keystone-adapter-knex-migrations` package have support for keystone-next projects?
When I do all like in instructions, I got the error:
```
$ yarn keystone-knex migrate-init
ℹ Command: keystone migrate-init
✖ Validating project entry file
Error: --entry=index.js was passed to keystone, but 'index.js' couldn't be found in /srv/k.dev.brick.ru/domains/api.k.dev.brick.ru/brick-api.
Ensure you're running keystone from within the root directory of the project.
    at getEntryFileFullPath (keystone/packages/keystone/bin/utils.js:63:7)
```

This is because in example projects the main entry file are moved to `keystone.ts`, but if I pass this file to script - I got other error:
```
$ yarn keystone-knex migrate-init --entry=keystone.ts
ℹ Command: keystone migrate-init --entry=keystone.ts
✖  
/srv/k.dev.brick.ru/domains/api.k.dev.brick.ru/brick-api/keystone.ts:1
import { config, createSchema } from '@keystone-next/keystone/schema';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at initMigrations (node_modules/keystone-adapter-knex-migrations/bin/commands/migrate-init.js:46:31)
error Command failed with exit code 1.
```

Can you provide the solution or workaround for this problem?

**Comment by josemf** [comment]
@MurzNN you might need to configure babel or any other method to transform your typescript entry file when using the keystone-knex commands. The script will import the contents from the entry file and run from there. If the entry file is anything else than Common JS this will fail.

Note this would also happen if you use `yarn create-tables` so it isn't specific to this adapter.

Make sure your environment supports running `keystone-knex` commands with typescript. This might depend on you project package.json but try to add the keystone-knex command in your scripts section:

```json
  "scripts": {
    "dev": "cross-env NODE_ENV=development DISABLE_LOGGING=true keystone dev",
    "build": "cross-env NODE_ENV=production keystone build",
    "start": "cross-env NODE_ENV=production keystone start",
    "create-tables": "cross-env CREATE_TABLES=true keystone create-tables",
    "migrate-init": "cross-env keystone-knex migrate-init --entry=keystone.ts"      
  },
```
